apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-servicehub
  namespace: platform-gitops
  labels:
spec:
  destination:
    namespace: platform-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    directory:
      recurse: true
    repoURL: 'https://github.com/milles9393/ocptest01-servicehub-apps.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
