apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicehub-ma
  namespace: helmappsofapps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: helmappsofapps
    server: https://kubernetes.default.svc
  source:
    path: servicehub-backend
    repoURL: https://github.com/milles9393/helm-basic.git
    targetRevision: master
    helm:
      values: |
        color:
          page: blue
